/**
 * Reads the robot's tuned PedroPathing constants out of TeamCode.
 *
 * Every number driving the time estimate, the velocity gradient and the
 * clearance margins was typed in by hand, which makes the whole model only as
 * good as eight guesses. The team has already measured several of them — that is
 * what PedroPathing's tuning process produces — and they are sitting in
 * `SwerveDrivetrainConstants.java` next to this tool. Reading them beats asking
 * someone to copy numbers between two files and keep them in step.
 *
 * What is *not* in there matters as much as what is. PedroPathing models no
 * acceleration limit at all (it is PIDF plus a power cap), states no maximum
 * turn rate, and has nothing corresponding to this tool's turn coupling. Those
 * stay guesses, and the import says so rather than quietly leaving them looking
 * as measured as the rest.
 */

export type Drivetrain = "swerve" | "mecanum";

/** A value read from the constants file, and where it came from. */
export interface ImportedConstant {
  /** The `Settings` field this lands on. */
  setting: string;
  label: string;
  value: number;
  /** The Java call it was read from, for showing the provenance. */
  source: string;
  /** Units, for display. */
  unit: string;
  /**
   * True when the number is the robot's measured ceiling rather than what the
   * follower holds in normal driving, so applying it straight makes the
   * estimate optimistic.
   */
  ceiling?: boolean;
  note?: string;
}

export interface TeamCodeConstants {
  drivetrain: Drivetrain;
  /** The file the values came from, repo-relative. */
  sourceFile: string;
  values: ImportedConstant[];
  /** Settings the constants file has no answer for, and why. */
  missing: Array<{ setting: string; label: string; reason: string }>;
}

/** Fields PedroPathing genuinely does not describe, so they stay hand-tuned. */
const NOT_IN_PEDRO: TeamCodeConstants["missing"] = [
  {
    setting: "maxAcceleration",
    label: "Max acceleration",
    reason:
      "PedroPathing models no acceleration limit — it is PIDF plus a power cap, so tuning produces no number for it.",
  },
  {
    setting: "aVelocity",
    label: "Max turn rate",
    reason:
      "The heading PIDF coefficients do not imply a rate limit, and nothing else in the constants states one.",
  },
  {
    setting: "turnCoupling",
    label: "Turn coupling",
    reason:
      "How much turning eats into driving speed is this tool's own model; PedroPathing has no equivalent.",
  },
  {
    setting: "maxLateralAcceleration",
    label: "Cornering grip",
    reason:
      "`centripetalScaling` is a correction gain rather than a sliding limit, so it does not convert to a grip figure.",
  },
];

/**
 * Pulls a `.someName(<number>)` builder argument out of Java source.
 *
 * A regex rather than a parser because these files are generated by a tuning
 * workflow and always take this shape; anything cleverer would be more to go
 * wrong for no benefit.
 */
export function readBuilderNumber(source: string, method: string): number | null {
  const pattern = new RegExp(`\\.\\s*${method}\\s*\\(\\s*(-?\\d+(?:\\.\\d+)?)\\s*\\)`);
  const match = pattern.exec(stripComments(source));
  if (!match) return null;
  const value = Number(match[1]);
  return Number.isFinite(value) ? value : null;
}

/**
 * Removes comments so a commented-out call is never read as live.
 *
 * These files carry alternates parked behind `//`, and picking one of those up
 * would silently import a number the robot is not using.
 */
export function stripComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/(^|[^:])\/\/[^\n]*/g, "$1");
}

/** Which drivetrain `config.jsonc` selects. */
export function readDrivetrain(configJsonc: string): Drivetrain | null {
  const match = /"drivetrain"\s*:\s*"([a-z]+)"/i.exec(stripComments(configJsonc));
  const value = match?.[1]?.toLowerCase();
  return value === "swerve" || value === "mecanum" ? value : null;
}

/**
 * Reads what the constants file can tell us about how the robot moves.
 *
 * `velocity` on the drivetrain constants is the tuned top speed. The zero-power
 * accelerations are how hard the robot slows with no power applied — its braking
 * ceiling, not what the follower sustains while still holding a line, which is
 * why it comes back flagged.
 */
export function parseTeamCodeConstants(
  drivetrain: Drivetrain,
  source: string,
  sourceFile: string,
): TeamCodeConstants {
  const values: ImportedConstant[] = [];
  const missing = [...NOT_IN_PEDRO];

  // A swerve states one top speed; a mecanum is tuned forward and sideways
  // separately, and the paths are driven forward, so that is the one that caps
  // the profile.
  const swerveVelocity = drivetrain === "swerve" ? readBuilderNumber(source, "velocity") : null;
  const forwardVelocity = readBuilderNumber(source, "xVelocity");
  const velocity = swerveVelocity ?? forwardVelocity;
  const velocitySource =
    swerveVelocity !== null
      ? `swerveConstants.velocity(${swerveVelocity})`
      : `mecanumConstants.xVelocity(${forwardVelocity})`;

  if (velocity !== null && velocity > 0) {
    values.push({
      setting: "maxVelocity",
      label: "Max velocity",
      value: round(velocity),
      source: velocitySource,
      unit: "in/s",
      note:
        swerveVelocity === null
          ? "Forward speed. A mecanum is slower sideways, and this tool profiles one speed, so the paths are timed as if driven forward."
          : undefined,
    });
  } else {
    missing.unshift({
      setting: "maxVelocity",
      label: "Max velocity",
      reason:
        "No `.velocity(...)` or `.xVelocity(...)` call found on the drivetrain constants.",
    });
  }

  const forwardZero = readBuilderNumber(source, "forwardZeroPowerAcceleration");
  if (forwardZero !== null && forwardZero !== 0) {
    values.push({
      setting: "maxDeceleration",
      label: "Max deceleration",
      value: round(Math.abs(forwardZero)),
      source: `followerConstants.forwardZeroPowerAcceleration(${forwardZero})`,
      unit: "in/s²",
      ceiling: true,
      note:
        "How hard the robot slows with no power applied. That is its braking ceiling, not what the follower holds while still tracking a line, so the estimate leans optimistic if you take it as-is.",
    });
  } else {
    missing.unshift({
      setting: "maxDeceleration",
      label: "Max deceleration",
      reason: "No `.forwardZeroPowerAcceleration(...)` call found.",
    });
  }

  return { drivetrain, sourceFile, values, missing };
}

/** Extra readings shown for context but not applied to any setting. */
export interface TeamCodeReference {
  label: string;
  value: number;
  unit: string;
  source: string;
}

export function parseTeamCodeReference(source: string): TeamCodeReference[] {
  const reference: TeamCodeReference[] = [];

  const sideways = readBuilderNumber(source, "yVelocity");
  if (sideways !== null) {
    reference.push({
      label: "Sideways speed",
      value: round(sideways),
      unit: "in/s",
      source: "mecanumConstants.yVelocity",
    });
  }

  const lateral = readBuilderNumber(source, "lateralZeroPowerAcceleration");
  if (lateral !== null) {
    reference.push({
      label: "Lateral braking",
      value: round(Math.abs(lateral)),
      unit: "in/s²",
      source: "followerConstants.lateralZeroPowerAcceleration",
    });
  }

  const mass = readBuilderNumber(source, "mass");
  if (mass !== null) {
    reference.push({
      label: "Robot mass",
      value: round(mass),
      unit: "kg",
      source: "followerConstants.mass",
    });
  }

  const centripetal = readBuilderNumber(source, "centripetalScaling");
  if (centripetal !== null) {
    reference.push({
      label: "Centripetal scaling",
      value: centripetal,
      unit: "",
      source: "followerConstants.centripetalScaling",
    });
  }

  return reference;
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

/** The change one imported constant would make, for showing before applying. */
export interface ConstantChange extends ImportedConstant {
  current: number | undefined;
  changed: boolean;
}

export function diffAgainstSettings(
  imported: ImportedConstant[],
  settings: Record<string, unknown>,
): ConstantChange[] {
  return imported.map((entry) => {
    const current = Number(settings?.[entry.setting]);
    const has = Number.isFinite(current);
    return {
      ...entry,
      current: has ? current : undefined,
      changed: !has || Math.abs(current - entry.value) > 1e-6,
    };
  });
}
