package org.firstinspires.ftc.teamcode.diagnostics.swerve;

import java.util.Locale;

/**
 * Renders live calibration back into Java source matching the shape of
 * {@code SwerveDrivetrainConstants}, so a bring-up session ends in a copy-paste rather than
 * transcribing numbers by hand.
 */
public final class SwerveExport {

    private SwerveExport() {
    }

    /**
     * @param pods pods in the order leftFront, rightFront, leftBack, rightBack
     */
    public static String generate(PodCal[] pods) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Swerve Bring-Up dashboard.\n");
        sb.append("// Paste into SwerveDrivetrainConstants.java, replacing the pod factories.\n\n");

        // kF is genuinely per-pod on this robot (front and back pods carry different loads), so it
        // is emitted inline rather than hoisted into a shared field like kP/kD.
        sb.append(String.format(Locale.US, "private static double kP = %.6f;%n", pods[0].kP));
        sb.append(String.format(Locale.US, "private static double kD = %.6f;%n", pods[0].kD));
        sb.append("\n");
        sb.append(String.format(Locale.US, "private static double dtLength = %.3f;%n", Math.abs(pods[0].podX)));
        sb.append(String.format(Locale.US, "private static double dtWidth = %.3f;%n%n", Math.abs(pods[0].podY)));

        String[] methods = {"leftFront", "rightFront", "leftBack", "rightBack"};
        for (int i = 0; i < pods.length && i < methods.length; i++) {
            sb.append(podMethod(methods[i], pods[i]));
            sb.append("\n");
        }
        return sb.toString();
    }

    private static String podMethod(String methodName, PodCal p) {
        String xExpr = (p.podX < 0 ? "-dtLength" : "dtLength");
        String yExpr = (p.podY < 0 ? "-dtWidth" : "dtWidth");

        return String.format(Locale.US,
                "private static CoaxialPod %s(HardwareMap hardwareMap) {%n"
                        + "    CoaxialPod pod = new CoaxialPod(hardwareMap, \"%s\", \"%s\", \"%s\",%n"
                        + "            new PIDFCoefficients(kP, 0, kD, %.6f),%n"
                        // Both directions use DcMotorSimple.Direction: CRServo.Direction is the
                        // same inherited enum, and this matches the imports the target file has.
                        + "            DcMotorSimple.Direction.%s,%n"
                        + "            DcMotorSimple.Direction.%s,%n"
                        + "            Math.toRadians(%.1f), new Pose(%s, %s),%n"
                        + "            %.3f, %.3f, %s);%n"
                        + "    pod.setMotorCachingThreshold(0.05);%n"
                        + "    pod.setServoCachingThreshold(0.05);%n"
                        + "    return pod;%n"
                        + "}%n",
                methodName,
                p.motorName, p.servoName, p.encoderName,
                p.kF,
                p.driveDirection.name(),
                p.servoDirection.name(),
                Math.toDegrees(p.angleOffsetRad),
                xExpr, yExpr,
                p.analogMin, p.analogMax,
                p.encoderReversed);
    }
}
