package org.firstinspires.ftc.teamcode.diagnostics.swerve;

import java.util.Locale;

/**
 * Renders live calibration back into Java source matching the shape of
 * {@code SwerveDrivetrainConstants}, so a bring-up session ends in a copy-paste rather than
 * transcribing numbers by hand.
 */
public final class SwerveExport {

    private SwerveExport() {
    }

    /**
     * @param pods pods in the order leftFront, rightFront, leftBack, rightBack
     */
    public static String generate(PodCal[] pods) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Swerve Bring-Up dashboard.\n");
        sb.append("// Paste into SwerveDrivetrainConstants.java, replacing the pod factories.\n\n");

        // Every gain is per-pod. Hoisting kP/kD into shared fields would silently publish one pod's
        // gains to all four - which reads as "three pods mysteriously wobble" once pasted.
        boolean sharedGains = true;
        for (PodCal p : pods) {
            if (p.kP != pods[0].kP || p.kD != pods[0].kD || p.kI != pods[0].kI) {
                sharedGains = false;
                break;
            }
        }

        if (sharedGains) {
            sb.append(String.format(Locale.US, "private static double kP = %.6f;%n", pods[0].kP));
            sb.append(String.format(Locale.US, "private static double kD = %.6f;%n", pods[0].kD));
            sb.append("\n");
        } else {
            sb.append("// Each pod carries its own kP/kD - they were tuned separately and differ.\n");
        }

        sb.append(String.format(Locale.US, "private static double dtLength = %.3f;%n", Math.abs(pods[0].podX)));
        sb.append(String.format(Locale.US, "private static double dtWidth = %.3f;%n%n", Math.abs(pods[0].podY)));

        String[] methods = {"leftFront", "rightFront", "leftBack", "rightBack"};
        for (int i = 0; i < pods.length && i < methods.length; i++) {
            sb.append(podMethod(methods[i], pods[i], sharedGains));
            sb.append("\n");
        }
        return sb.toString();
    }

    private static String podMethod(String methodName, PodCal p, boolean sharedGains) {
        String xExpr = (p.podX < 0 ? "-dtLength" : "dtLength");
        String yExpr = (p.podY < 0 ? "-dtWidth" : "dtWidth");

        String gains = sharedGains
                ? String.format(Locale.US, "kP, %.6f, kD, %.6f", p.kI, p.kF)
                : String.format(Locale.US, "%.6f, %.6f, %.6f, %.6f", p.kP, p.kI, p.kD, p.kF);

        return String.format(Locale.US,
                "private static CoaxialPod %s(HardwareMap hardwareMap) {%n"
                        + "    CoaxialPod pod = new CoaxialPod(hardwareMap, \"%s\", \"%s\", \"%s\",%n"
                        + "            new PIDFCoefficients(%s),%n"
                        // Both directions use DcMotorSimple.Direction: CRServo.Direction is the
                        // same inherited enum, and this matches the imports the target file has.
                        + "            DcMotorSimple.Direction.%s,%n"
                        + "            DcMotorSimple.Direction.%s,%n"
                        + "            Math.toRadians(%.1f), new Pose(%s, %s),%n"
                        + "            %.3f, %.3f, %s);%n"
                        + "    pod.setMotorCachingThreshold(0.05);%n"
                        + "    pod.setServoCachingThreshold(%.3f);%n"
                        + "%s"
                        + "    return pod;%n"
                        + "}%n",
                methodName,
                p.motorName, p.servoName, p.encoderName,
                gains,
                p.driveDirection.name(),
                p.servoDirection.name(),
                Math.toDegrees(p.angleOffsetRad),
                xExpr, yExpr,
                p.analogMin, p.analogMax,
                p.encoderReversed,
                p.servoCaching,
                extras(p));
    }

    /**
     * Emits the Ruckus-patch pod settings, and only the ones that are doing something.
     *
     * <p>Each is a no-op at its default, so writing them all out unconditionally would put four
     * lines of noise in every generated pod for the benefit of the one that is set. A pod that
     * uses none of them exports exactly as it did before these existed.
     */
    private static String extras(PodCal p) {
        StringBuilder sb = new StringBuilder();
        if (p.kS != 0.0) {
            sb.append(String.format(Locale.US,
                    "    pod.setStaticFriction(%.4f, Math.toRadians(%.2f));%n", p.kS, p.kSBandDeg));
        }
        if (p.kI != 0.0) {
            sb.append(String.format(Locale.US,
                    "    pod.setTurnIntegralSettings(%.4f, Math.toRadians(%.2f), "
                            + "Math.toRadians(%.2f));%n",
                    p.kILimit, p.kIBandDeg, p.kIResetDeg));
        }
        if (p.derivativeOnMeasurement) {
            sb.append("    pod.setDerivativeOnMeasurement(true);%n".replace("%n", "\n"));
        }
        if (p.pulsed) {
            sb.append(String.format(Locale.US,
                    "    pod.setPulsedApproach(true, Math.toRadians(%.2f), Math.toRadians(%.2f), "
                            + "%.4f, %.4f, Math.toRadians(%.1f), %.4f);%n",
                    p.pulseBandDeg, p.pulseTolDeg, p.pulsePower, p.pulseMs / 1000.0,
                    p.pulseStationaryDegPerSec, p.pulseCoastMs / 1000.0));
        }
        return sb.toString();
    }
}
